### ISSUE TITLE
Error code 2502 - Cannot install 

### ISSUE THREAD

**Issue by djkilla1337** [OSM-Made/Orbis-Suite#2]
![cf1b2349aff8be89920d85df6bf79f4d](https://user-images.githubusercontent.com/73022507/96336106-d4584880-106c-11eb-97e0-6dcb32b44fd3.png)

**Comment by OSM-Made** [comment]
The issue with this as far as I can tell is an issue with your machine. The error is with the windows installer its self and its because the user does not have full access to the C:\Windows\Temp folder.

**Comment by djkilla1337** [comment]
Do you know if there is anyway to fix this issue? I am on my own computer and I run it as Admin. I'm on Windows 10 Pro

**Comment by OSM-Made** [comment]
You could try following this https://kb.foxitsoftware.com/hc/en-us/articles/360040660391-Fix-Error-2502-and-2503-while-installing-or-uninstalling#method1 let me know if this solves the issues.
